spring:
  datasource:
    url: jdbc:postgresql://horton.db.elephantsql.com:5432/rphizuhl
    username: rphizuhl
    password: BAa04qS6aQJd5VR5UQE0CFQkeaWlmhh6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect